### ISSUE TITLE
Serverless function - Puppeteer / Chromium

### ISSUE THREAD

**Issue by Jamesllllllllll** [Jamesllllllllll/beacons-link-checker#2]
I tested this serverless function in another Next project that uses the Pages router. 

It is working and returns the expected data when submitting a Beacons username.

However, the same UI & serverless function returns the error below in the terminal for this commit https://github.com/Jamesllllllllll/beacons-link-checker/commit/5fa7a7f52d0327dca121b9c3c3d37c4e1c8bb534 

I think it is an issue with the AppRouter, so I will be working on **layout.js** to look for a solution.

```
- wait compiling /_error (client and server)...
- event compiled client and server successfully in 1006 ms (170 modules)
- wait compiling /page (client and server)...
- event compiled client and server successfully in 3.7s (1426 modules)
- wait compiling...
- event compiled successfully in 336 ms (810 modules)
- wait compiling /api/checkBeacon (client and server)...
- event compiled successfully in 509 ms (619 modules)
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
    at AppContainer (C:\Users\james\Documents\Projects\Side Projects\beacons-link-checker\node_modules\next\dist\server\render.js:323:29)
    at AppContainerWithIsomorphicFiberStructure (C:\Users\james\Documents\Projects\Side Projects\beacons-link-checker\node_modules\next\dist\server\render.js:359:57)
    at div
    at Body (C:\Users\james\Documents\Projects\Side Projects\beacons-link-checker\node_modules\next\dist\server\render.js:659:21)
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
    at AppContainer (C:\Users\james\Documents\Projects\Side Projects\beacons-link-checker\node_modules\next\dist\server\render.js:323:29)
    at AppContainerWithIsomorphicFiberStructure (C:\Users\james\Documents\Projects\Side Projects\beacons-link-checker\node_modules\next\dist\server\render.js:359:57)
    at div
    at Body (C:\Users\james\Documents\Projects\Side Projects\beacons-link-checker\node_modules\next\dist\server\render.js:659:21)
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
    at PathnameContextProviderAdapter (C:\Users\james\Documents\Projects\Side Projects\beacons-link-checker\node_modules\next\dist\shared\lib\router\adapters.js:84:11)
    at AppContainer (C:\Users\james\Documents\Projects\Side Projects\beacons-link-checker\node_modules\next\dist\server\render.js:323:29)
    at AppContainerWithIsomorphicFiberStructure (C:\Users\james\Documents\Projects\Side Projects\beacons-link-checker\node_modules\next\dist\server\render.js:359:57)
    at div
    at Body (C:\Users\james\Documents\Projects\Side Projects\beacons-link-checker\node_modules\next\dist\server\render.js:659:21)
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
    at PathnameContextProviderAdapter (C:\Users\james\Documents\Projects\Side Projects\beacons-link-checker\node_modules\next\dist\shared\lib\router\adapters.js:84:11)
    at AppContainer (C:\Users\james\Documents\Projects\Side Projects\beacons-link-checker\node_modules\next\dist\server\render.js:323:29)
    at AppContainerWithIsomorphicFiberStructure (C:\Users\james\Documents\Projects\Side Projects\beacons-link-checker\node_modules\next\dist\server\render.js:359:57)
    at div
    at Body (C:\Users\james\Documents\Projects\Side Projects\beacons-link-checker\node_modules\next\dist\server\render.js:659:21)
```

The exact same code produces this result in another Next project using the Pages router:

![Beacon Success](https://github.com/Jamesllllllllll/beacons-link-checker/assets/125431058/d428d4dc-f31f-4a9a-9278-28daac81580b)

**Comment by Jamesllllllllll** [comment]
Ok - It was the App Router's method of API calls.

With the **Pages** Router, you can create a function at `/api/myFunction.js` and `fetch('/api/myFunction?myParam=${param}')`

The function is a default export like so:

`export default async function handler(req, res) { ...`

The default method is GET, and you can declare otherwise in the handler.

---

However, in the **App** router you need to structure the files like `/api/myFunction/route.js` and export named functions for the request method like so:

`export async function GET(req, res) { ...`

---

I got it to work locally and deployed it to development preview on Vercel.

Now there is an issue with opening Chromium. This makes me wonder - is it even possible to run Puppeteer/Chromium on the deployed Node runtime??

Here are the logs from Vercel:

```
checkBeacon running...
Username: api
URL: https://beacons.ai/api
Opening the browser......
Could not create a browser instance => :  Error: Could not find Chrome (ver. 116.0.5845.96). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/sbx_user1051/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:300:27)
    at ChromeLauncher.executablePath (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:180:25)
    at ChromeLauncher.computeLaunchArguments (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:97:37)
    at async ChromeLauncher.launch (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:79:28)
```

**Comment by Jamesllllllllll** [comment]
Chromium is too large for it to be used in a Vercel serverless function. 

I've tried using the _playwright-core_ and _chrome-aws-lambda_ packages referenced by a few tutorials [like this one](https://www.umuttufanoglu.dev/blog/puppeteer-nextjs), and I'm encountering a Webpack loader problem [like this one](https://github.com/alixaxel/chrome-aws-lambda/issues/224).

The above issue [links to this solution](https://github.com/vercel/next.js/discussions/26478), but I didn't have `target: serverless` in next.config.js. Going to take a break from this for the night!

**Comment by Jamesllllllllll** [comment]
Found a [solution](https://github.com/alixaxel/chrome-aws-lambda/issues/200#issuecomment-1090321840) that reduces `chrome-aws-lambda` bundle size by going with a smaller version. Still, the function is <1MB away from max.

**Comment by Jamesllllllllll** [comment]
The serverless function was reaching the 10sec limit for Vercel hobby plans, so I got a free Pro trial - it takes 20-25 seconds to fire up the headless Chromium browser, navigate to the page and read the contents!

I added the link checking functionality as well.

The UI ain't pretty yet, but it's working! 

https://beacons-link-checker-git-development-jamesllllllllll-s-team.vercel.app/
